employeeManagement/account/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, IntegerField, DateField, PasswordField, SubmitField
from wtforms.fields.html5 import EmailField
from wtforms.validators import InputRequired, DataRequired, Length, ValidationError, Email
from employeeManagement.models import User
from employeeManagement.auth.routes import current_user


class UpdateAccountForm(FlaskForm):
    username = StringField("Username *", validators=[
        InputRequired("Input is required!"),
        DataRequired("Data is required!"),
        Length(min=5, max=20, message="Username must be between 5 and 20 characters long")
    ])
    first_name = StringField("First Name*", validators=[
        InputRequired("Input is required!"),
        DataRequired("Data is required!"),
        Length(min=3, max=20, message="First name must be between 3 and 20 characters long")
    ])
    last_name = StringField("Last Name")
    phone = IntegerField("Phone *", validators=[
        InputRequired("Input is required!"),
        DataRequired("Data is required!")
    ])
    dob = DateField("Date of birth*", validators=[
        InputRequired("Input is required!"),
        DataRequired("Data is required!")
    ])
    email = EmailField("Email *", validators=[
        InputRequired("Input is required!"),
        DataRequired("Data is required!"),
        Length(min=5, max=30, message="Email must be between 5 and 30 characters long"),
        Email("You did not enter a valid email!")
    ])
    password = PasswordField("Password *", validators=[
        InputRequired("Input is required!"),
        DataRequired("Data is required!"),
        Length(min=10, max=40, message="Password must be between 10 and 40 characters long")
    ])
    location = StringField("Your location (e.g. city, country)", validators=[
        InputRequired("Input is required!"),
        DataRequired("Data is required!"),
        Length(min=3, max=40, message="Location must be between 3 and 40 characters long")
    ])
    submit = SubmitField("Update")

    def validate_username(form, field):
        user = User.query.filter_by(username=field.data).first()

        if current_user.is_admin():
            return
        if user != current_user:
            raise ValidationError("Username already exists.")

    def validate_email(form, field):
        user = User.query.filter_by(email=field.data).first()
        if current_user.is_admin():
            return
        if user != current_user:
            raise ValidationError("Email already exists.")

    def validate_phone(form, field):
        if len(str(field.data)) != 10:
            raise ValidationError("Phone number should be 10 digits long")
        user = User.query.filter_by(phone=field.data).first()
        if current_user.is_admin():
            return
        if user != current_user:
            raise ValidationError("Phone number already exists.")

employeeManagement/account/routes.py
from flask import Blueprint, render_template, flash, url_for, redirect, abort
from employeeManagement.auth.routes import current_user, login_required, logout_user
from employeeManagement.models import User
from employeeManagement import db
from werkzeug.utils import escape, unescape
from employeeManagement.account.forms import UpdateAccountForm

account = Blueprint("account", __name__, template_folder="templates")


@account.route("/profile/<username>")
@login_required
def show(username):
    user = User.query.filter_by(username=username).first()
    if user == current_user or current_user.is_admin():
        return render_template("show_account.html", user=user)
    return abort(403)


@account.route("/edit/<username>", methods=["GET", "POST"])
@login_required
def edit(username):
    form = UpdateAccountForm()
    user = User.query.filter_by(username=username).first()
    if user == current_user or current_user.is_admin():
        if form.validate_on_submit():
            user.location = escape(form.location.data)
            user.username = form.username.data
            user.first_name = escape(form.first_name.data)
            user.last_name = escape(form.last_name.data)
            user.email = form.email.data
            user.phone = form.phone.data
            user.dob = form.dob.data
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash("Account has been updated.", "success")
            return redirect(url_for("account.show", username=user.username))

        form.location.data = unescape(user.location)
        form.username.data = user.username
        form.first_name.data = unescape(user.first_name)
        form.last_name.data = unescape(user.last_name)
        form.email.data = user.email
        form.phone.data = user.phone
        form.dob.data = user.dob
        return render_template("edit_account.html", form=form, user=user)
    return abort(403)


@account.route("/delete", methods=["POST"])
@login_required
def delete():
    db.session.delete(current_user)
    db.session.commit()
    logout_user()
    flash("Your account has been deleted.", "success")
    return redirect(url_for("main.home"))

employeeManagement/account/templates/edit_account.html
{% extends 'base.html' %}
{% block title %}Update account {{ current_user.first_name }} {% endblock %}
{% from '_error_messages.html' import field_error_messages, error_messages %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <h1>Update account - <a href="{{ url_for('account.show', username=user.username) }}">{{ user.username }}</a></h1><hr>
    <form method="POST" action="{{ url_for('account.edit', username=user.username) }}">
      {{ form.csrf_token }}
      {{ error_messages(form.errors) }}

      <div class="form-group">
        {{ form.username.label }}
        {{ form.username(class="form-control") }}
        {{ field_error_messages(form.username) }}
      </div>
      <div class="form-group">
        {{ form.first_name.label }}
        {{ form.first_name(class="form-control") }}
        {{ field_error_messages(form.first_name) }}
      </div>
      <div class="form-group">
        {{ form.last_name.label }}
        {{ form.last_name(class="form-control") }}
        {{ field_error_messages(form.last_name) }}
      </div>
      <div class="form-group">
        {{ form.email.label }}
        {{ form.email(class="form-control") }}
        {{ field_error_messages(form.email) }}
      </div>
      <div class="form-group">
        {{ form.phone.label }}
        {{ form.phone(class="form-control") }}
        {{ field_error_messages(form.phone) }}
      </div>
      <div class="form-group">
        {{ form.dob.label }}
        {{ form.dob(class="form-control") }}
        {{ field_error_messages(form.dob) }}
      </div>
      <div class="form-group">
        {{ form.password.label }}
        {{ form.password(class="form-control") }}
        {{ field_error_messages(form.password) }}
      </div>
      <div class="form-group">
        {{ form.location.label }}
        {{ form.location(class="form-control") }}
        {{ field_error_messages(form.location) }}
      </div>
      <hr>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary form-control") }}
      </div>
    </form>
  </div>
</div>
{% endblock %}

employeeManagement/account/templates/show_account.html
{% extends 'base.html' %}
{% block title %}{{ user.first_name }} {% endblock %}
{% if current_user == user %}
{% set active_page = 'account' %}
{% endif %}

{% block content %}
<div class="row">
  <div class="col-lg-10">
    <div class="card mt-4">
      <div class="card-body">
        <h3 class="card-title">
        {{ user.first_name }}
            {% if user.last_name %}
            {{ user.last_name }}
            {% endif %}
        <small>
      		{% if user.is_role(Role.EMPLOYEE) %}
      		(Employee)
         	{% endif %}
            {% if user.is_role(Role.ADMIN) %}
            (Admin)
            {% endif %}
      	</small>
        {% if user == current_user or current_user.is_admin() %}
          <div class="button-actions">
      	    <a href="{{ url_for('account.edit', username=user.username) }}" class="btn btn-primary">Update account</a>
            {% if not current_user.is_admin() %}
            <form class="delete-form" method="POST" action="{{ url_for('account.delete') }}">
              <input class="btn btn-danger" type="submit" name="deleteAccount"
              value="Delete account"
              onclick="return confirm('Are you sure that you want to permanently delete your account?')">
      	    </form>
            {% endif %}
            {% if current_user.is_admin() %}
            <form class="delete-form" method="POST" action="{{ url_for('admin.delete_user', user_id=user.id) }}">
              <input class="btn btn-danger" type="submit" name="submit"
              value="Delete user"
              onclick="return confirm('Are you sure that you want to permanently delete this user?')">
      	    </form>
            {% endif %}
      		</div>

        {% endif %}
  	    </h3>
          <p><b>First Name:</b> {{ user.first_name }}</p>
          {% if user.last_name %}
          <p><b>Last Name:</b> {{ user.last_name }}</p>
          {% endif %}
          <p><b>Email:</b> {{ user.email }}</p>
          <p><b>Phone:</b> {{ user.phone }}</p>
          <p><b>Date of birth:</b> {{ user.dob }}</p>
        <p><b>Location:</b> {{ user.location }}</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}