employeeManagement/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField
from wtforms.validators import InputRequired, DataRequired


class SearchForm(FlaskForm):
    search = StringField("Search (Username, First Name, Last Name, Email, Location)...", validators=[
                                    InputRequired("Input is required!"),
                                    DataRequired("Data is required!")
                                ])
    submit = SubmitField("Search")

employeeManagement/main/routes.py
import os
import requests
import json
from flask import Blueprint, render_template
from employeeManagement.auth.routes import current_user, role_required
from employeeManagement.models import User, Role
from employeeManagement.main.forms import SearchForm


main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
def home():
    if current_user.is_admin():
        users = User.query.all()
        form = SearchForm()
    else:
        form = ""
        users = ""
    return render_template('home.html', form=form, users=users, search_flag=False)


@main.route('/search', methods=["GET", "POST"])
@role_required(Role.ADMIN)
def search():
    form = SearchForm()
    if form.validate_on_submit():
        keyword = form.search.data
        params = {'keyword': keyword}
        users = requests.get('http://'+os.getenv('HOST')+'/api/search_admin', params=params)
        form.search.data = ""
        users = json.loads(users.text)
        return render_template('home.html', form=form, users=users, search_flag=True
                               , keyword=keyword, count=len(users))

employeeManagement/main/templates/home.html
{% extends 'base.html' %}
{% set active_page = 'home' %}
{% block title %}
Home
{% endblock %}

{% block content %}

{% if current_user.is_authenticated() %}
  {% include 'home/_authenticated.html' %}
{% else %}
  {% include 'home/_landing.html' %}
{% endif %}

{% endblock %}

employeeManagement/main/templates/home/_authenticated.html
{% if current_user.is_role(Role.EMPLOYEE) %}
<div class="row">
  <div class="col-lg-10">
      <div class="card card-outline-secondary my-4">
        <div class="card-header">
          Welcome, {{ current_user.username }}
        </div>
        <div class="card-body">
          <h4>
            Username:
            <a href="{{ url_for('account.show', username=current_user.username) }}">{{ current_user.username }}</a>
          </h4>
          <h4>
            Name:
            <small>{{ current_user.first_name }}</small>
            {% if current_user.last_name %}
            <small>{{ current_user.last_name }}</small>
            {% endif %}
          </h4>
          <h4>
            Email:
            <small>{{ current_user.email }}</small>
          </h4>
          <h4>
            Phone:
            <small>{{ current_user.phone }}</small>
          </h4>
          <h4>
            Date of birth:
            <small>{{ current_user.dob }}</small>
          </h4>
          <h4>
            Location:
          <small>{{ current_user.location }}</small>
          </h4>
          <hr class="form-border">
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% if current_user.is_role(Role.ADMIN) %}
  {% block search %}
  <div class="row">
    <div class="col-lg-10">
    <form method="POST" action="{{ url_for('main.search') }}">
      {{ form.csrf_token }}
          <div class="md-col-3 form-group">
            {{ form.search(class="form-control",
            placeholder="Search (Username, First Name, Last Name, Email, Location)...") }}
          </div>
          <div class="form-group">
            {{ form.submit(class="btn btn-primary form-control") }}
          </div>
    </form>
    </div>
  </div>
  {% endblock %}
<div class="row">
  <div class="col-lg-10">
    <form method="GET" action="{{ url_for('admin.add_user') }}">
            <input class="btn btn-primary" type="submit" style="margin-top:10px" name="submit" value="Add user">
          </form>
    {% if not search_flag %}
      <div class="card card-outline-secondary my-4">
        <div class="card-header">
          All users
        </div>
        <div class="card-body">
          {% if users %}
          {% for user in users %}
          <h4>
            Username:
            <a href="{{ url_for('account.show', username=user.username) }}">{{ user.username }}</a>
            <small>
              {% if user.is_role(Role.EMPLOYEE) %}
              (employee)
              {% endif %}
              {% if user.is_admin() %}
              (admin)
              {% endif %}
            </small>
          </h4>
          <h4>
            Name:
            <small>{{ user.first_name }}</small>
            {% if user.last_name %}
            <small>{{ user.last_name }}</small>
            {% endif %}
          </h4>
          <h4>
            Email:
            <small>{{ user.email }}</small>
          </h4>
          <h4>
            Phone:
            <small>{{ user.phone }}</small>
          </h4>
          <h4>
            Date of birth:
            <small>{{ user.dob }}</small>
          </h4>
          <h4>
            Location:
          <small>{{ user.location }}</small>
          </h4>
          <form method="POST" action="{{ url_for('admin.delete_user', user_id=user.id) }}">
            <input class="btn btn-danger" type="submit" style="margin-top:10px" name="submit" value="Delete user"
            onclick="return confirm('Are you sure that you want to permanently delete this user?')">
          </form>
          <hr class="form-border">
          {% endfor %}
          {% endif %}
        </div>
      </div>
    {% endif %}
    {% if search_flag %}
      <div class="card card-outline-secondary my-4">
        <div class="card-header">
          Search results for {{ keyword }} - {{ count }} results found
        </div>
        <div class="card-body">
          {% if users %}
          {% for user in users %}
          <h4>
            Username:
            <a href="{{ url_for('account.show', username=user.username) }}">{{ user["username"] }}</a>
          </h4>
          <h4>
            Name:
            <small>{{ user["first_name"] }}</small>
            {% if user["last_name"] %}
            <small>{{ user["last_name"] }}</small>
            {% endif %}
          </h4>
          <h4>
            Email:
            <small>{{ user["email"] }}</small>
          </h4>
          <h4>
            Phone:
            <small>{{ user["phone"] }}</small>
          </h4>
          <h4>
            Date of birth:
            <small>{{ user["dob"] }}</small>
          </h4>
          <h4>
            Location:
          <small>{{ user["location"] }}</small>
          </h4>
          <form method="POST" action="{{ url_for('admin.delete_user', user_id=user['id']) }}">
            <input class="btn btn-danger" type="submit" style="margin-top:10px" name="submit" value="Delete user"
            onclick="return confirm('Are you sure that you want to permanently delete this user?')">
          </form>
          <hr class="form-border">
          {% endfor %}
          {% endif %}
        </div>
      </div>
    {% endif %}
    </div>
  </div>
</div>
{% endif %}

employeeManagement/main/templates/home/_landing.html
<main role="main">
    <div class="jumbotron" style="background: url('{{ url_for('static', filename='images/landing.jpg') }}')  center center;background-size: cover">
    <div class="container landing-box">
      <h1 class="display-3 landing-text">Welcome to Employee Management</h1>
      <p style="padding-bottom: 2rem"></p>
    </div>

  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-1">
        <br>
        <h2>New employee?</h2>
        <p><a class="btn btn-primary" href="{{ url_for('auth.register') }}" role="button">Join now »</a></p>
      </div>
      <div class="col-md-5 offset-md-2">
        <br>
        <h2>Existing employee?</h2>
        <p><a class="btn btn-primary" href="{{ url_for('auth.login') }}" role="button">Login now »</a></p>
      </div>
    </div>
    <hr>
  </div>
</main>