employeeManagement/main/routes.py
import os
import requests
import json
from flask import Blueprint, render_template
from employeeManagement.auth.routes import current_user, role_required
from employeeManagement.models import User, Role
from employeeManagement.main.forms import SearchForm


main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
def home():
    if current_user.is_admin():
        users = User.query.all()
        form = SearchForm()
    else:
        form = ""
        users = ""
    return render_template('home.html', form=form, users=users, search_flag=False)


@main.route('/search', methods=["GET", "POST"])
@role_required(Role.ADMIN)
def search():
    form = SearchForm()
    if form.validate_on_submit():
        keyword = form.search.data
        params = {'keyword': keyword}
        users = requests.get('http://'+os.getenv('HOST')+'/api/search_admin', params=params)
        form.search.data = ""
        users = json.loads(users.text)
        return render_template('home.html', form=form, users=users, search_flag=True
                               , keyword=keyword, count=len(users))

employeeManagement/templates/_error_messages.html
{% macro error_messages(errors) %}
{% if errors %}
<div class="alert alert-danger">
  {% for field in errors %}
    <b>{{ field | capitalize }} field has following errors:</b><br>
    {% for error in errors[field] %}
    {{ error }}<br>
    {% endfor %}
  {% endfor %}
</div>
{% endif %}
{% endmacro %}

{% macro field_error_messages(field) %}
{% if field.errors %}
<br>
<ul>
{% for error in field.errors %}
<li style="color:red">
  {{ error }}
</li>
{% endfor %}
</ul>
{% endif %}
{% endmacro %}

employeeManagement/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <div class="container">
      <a href="{{ url_for('main.home') }}" class="navbar-brand">
        Employee Management
      </a>
      <button class="navbar-toggler" type="button"
              data-toggle="collapse" data-target="#navbarResponsive"
              aria-controls="navbarResponsive" aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item {{ 'active' if active_page == 'home' }}">
            <a href="{{ url_for('main.home') }}" class="nav-link">Home</a>
          </li>
          {% if current_user.is_authenticated() %}
          <li class="nav-item {{ 'active' if active_page == 'account' }}">
            <a href="{{ url_for('account.show', username=current_user.username) }}" class="nav-link">Account ({{ current_user.username }})</a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
          </li>
          {% else %}
          <li class="nav-item {{ 'active' if active_page == 'register' }}">
            <a href="{{ url_for('auth.register') }}" class="nav-link">Register</a>
          </li>
          <li class="nav-item {{ 'active' if active_page == 'login' }}">
            <a href="{{ url_for('auth.login') }}" class="nav-link">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for type, content in messages %}
                <div class="alert alert-{{ type }} alert-dismissible my-4" role="alert">
                    <button type="button" class="close"
                    data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                    {{ content }}
                </div>
            {% endfor %}
      {% endif %}
    {% endwith %}
    {% block content %}
      {% block search %}
        {% endblock %}
      {% endblock %}
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      {% block javascript %}{% endblock %}
</body>
</html>